### ISSUE TITLE
No ID Attribute for Tag Field

### ISSUE THREAD

**Issue by hepalienn** [rossshannon/pincushion#11]
I use this in conjunction with another script that autofills some fields by passing them through the query string on the URL, and the tags field in Pincushion doesn't seem to have an "id" or "name" attribute to allow it to do that. Could that be added? Also, the ability to default to checking private/read later would be useful as well.

**Comment by rossshannon** [comment]
@hepalienn The base `<input>` element does have both `id` and `name` defined, but what you’re seeing in the DOM output is the generated output after instantiating the Selectize library on the input.

You could achieve what you’re aiming to do by calling `$('#tags')[0].selectize.addItem('tag_name')` https://selectize.dev/docs.html#usage

![Screen Shot 2021-06-14 at 23 07 26](https://user-images.githubusercontent.com/4503044/121968589-8403c880-cd6a-11eb-954d-360f8f4d82ba.png)

I added the option to pass `&private=true&toread=true` in the URL to set the checkboxes by default in https://github.com/rossshannon/pincushion/commit/ca821bacec1010699c6fbad0dacec7977fa55a84
